### ISSUE TITLE
Publish the latest version

### ISSUE THREAD

**Issue by ochrons** [marklister/base64#10]
I could find only 0.1.1 from Maven Central, nothing more recent than that.

**Comment by marklister** [comment]
I'll look at it today

**Comment by marklister** [comment]
I expect to publish v0.2.1  on 26 Feb.  Sorry for the hold up.

**Comment by marklister** [comment]
It should reflect soon.

**Comment by ochrons** [comment]
Great! I'll update ScalaFiddle to use the dependency instead of copy/pasting the code :)
