### ISSUE TITLE
Using '=' for padding does not work for URLs

### ISSUE THREAD

**Issue by ochrons** [marklister/base64#11]
When coding a query parameter to base64, the padding `=`s make it invalid. Some other URI compatible character should be used instead.

**Comment by marklister** [comment]
The rfc says
 ```
The pad character "=" is typically percent-encoded when used in an
   URI [9], but if the data length is known implicitly, this can be
   avoided by skipping the padding; see section 3.2.
```
Just thinking out loud here.

**Comment by ochrons** [comment]
Yes, currently I need to run the base64 result through URL escaping to make that happen. But since the code already has special version of b64 for URLs (to avoid escaping), this shoud be part of that feature.

**Comment by marklister** [comment]
Sounds reasonable, so if I pad with `%3D` that should do the trick? And I guess I should do the same for decoding?

**Comment by ochrons** [comment]
Or since you're not following official base64 encoding anyway, just choose a character that is compatible with URL like `.`

**Comment by marklister** [comment]
I've pushed to master, can you have a look and see what you think?

```
scala> implicit val e= Base64.base64Url
e: com.github.marklister.base64.Base64.B64Scheme = B64Scheme([C@5b590f33,false,<function1>,<function1>)

scala> "abc".getBytes.toBase64
res0: String = YWJj

scala> "abcd".getBytes.toBase64
res1: String = YWJjZA%3D%3D

scala> res1.toByteArray.map(_.toChar)
res2: Array[Char] = Array(a, b, c, d)
```

I've tried to follow the RFC as closely as possible.  Where have I tripped up?

**Comment by ochrons** [comment]
LGTM

**Comment by marklister** [comment]
v0.2.2 pushed to maven central.  Thanks @ochrons for the input!
