### ISSUE TITLE
0.2.5 jars are empty on maven central

### ISSUE THREAD

**Issue by erinmez** [marklister/base64#20]
Hi @marklister
Thanks for this little compact library! However, I noticed that jars don't contain any class/sjs files. 0.2.4 worked like a charm.

http://central.maven.org/maven2/com/github/marklister/base64_sjs0.6_2.12/0.2.5/base64_sjs0.6_2.12-0.2.5.jar
http://central.maven.org/maven2/com/github/marklister/base64_2.12/0.2.5/base64_2.12-0.2.5.jar

**Comment by marklister** [comment]
Thanks, will have a look now!

**Comment by marklister** [comment]
0.2.4 is functionally equivalent.  0.2.5 was supposed to be compiled for scala 2.13

**Comment by marklister** [comment]
Should be fixed with 0.2.6.  Please ping back here if not.  Support for scala 2.10 dropped but unfortunately Bintray creates empty jars for dropped versions.  So there are empty jars for 2.10 and 2.10-M2.  Not sure how to fix that.  Thanks for reporting!

**Comment by erinmez** [comment]
Thanks a lot for the quick turnaround! I checked it and it works (via Bintray).
