### ISSUE TITLE
Release with latest scalajs 1.x?

### ISSUE THREAD

**Issue by erinmez** [marklister/base64#23]
Hi @marklister

I was wondering whether you could release a new version against the latest scalajs? It's actually luckily humming along if it weren't for those big upgrades :-)

Thanks a lot,
Tanju

**Comment by marklister** [comment]
Hope to have this done in a day.

**Comment by marklister** [comment]
0.2.10 should (hopefully) do the trick.  I'll update the tests and build files later.

**Comment by erinmez** [comment]
Thanks a lot @marklister , works like a charm! See you again when Scala 3 comes around 🤣

**Comment by marklister** [comment]
Hopefully I can still figure out Sonatype then! ;)
