### ISSUE TITLE
Encoding is not compatible with Browser decoding

### ISSUE THREAD

**Issue by l15k4** [marklister/base64#5]
Hey, I compiled it to javascript using [scala-js](http://www.scala-js.org/) and if you do something like : 
```
href = "data:application/octet-stream;base64," + data.stripMargin.getBytes.toBase64
```
Then the downloaded file ends with some incorrectly decoded characters, otherwise it is alright. So I suspect that the Webkit/Chrome decoding is not compatible with this base64 encoding...

Btw to make this scala-js compatible one just need to comment out the specs2 test suite (that doesn't compile to javascript) or rewrite it using some scala-js compliant testing framework like [utest](https://github.com/lihaoyi/utest) and add plugin : 
```
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.0-M3")
``` 
and enable it : 
```
lazy val base64 = (project in file(".")).enablePlugins(org.scalajs.sbtplugin.ScalaJSPlugin)
```

**Comment by l15k4** [comment]
Anyway using [btoa](https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64.btoa) is a better idea. I just wanted to let you know that it might be something wrong with it if the encoder is not compliant with third party decoders. It means that stuff must be necessarily encoded and decoded by this codec.

**Comment by l15k4** [comment]
I'm pasting the answer of Sébastien Doeraene, the creator of scala-js :

The Scala implementation you found doesn't work in Scala.js because of this:
java.nio.ByteBuffer.allocate(8).putLong(r).array().takeRight(3)

ByteBuffer.putLong() is not (yet) implemented. 
**Note however that this line is super inefficient to produce the desired result. It is much better to do
Array((r >> 12).toByte, (r >> 6).toByte, r.toByte)
It's even shorter ^^**

But yes, anyway btoa is the way to go in browsers, unless you want a cross-compiling source.

**Comment by l15k4** [comment]
In case you were interested in the javascript benchmark of your library, [see](https://groups.google.com/d/msg/scala-js/En8WL-WIY_Q/147WEVIIOKAJ)

**Comment by marklister** [comment]
https://groups.google.com/forum/#!msg/scala-js/En8WL-WIY_Q/147WEVIIOKAJ

The analysis is brutally accurate.  This implementation is is very inefficient and totally unacceptable for bulk encoding or decoding.  I'll look into producing a scala-js compatible version but converting the implementation to bit - twiddling arrays is out of scope for me.

**Comment by marklister** [comment]
The conversion to  is complete except for a snafu involving cross compiling in js and the jvm.  I'll push the update once I've got the tests running in js.  I also made a note about performance in the read me and implemented Sebastian's array output suggestion. I believe there's a place for a small scales only solution.

**Comment by marklister** [comment]
v 0.1.1 fixes.
