### ISSUE TITLE
Strict padding unnecessary -- causes JS interop problem

### ISSUE THREAD

**Issue by bblfish** [marklister/base64#6]
JS WebCrytpoAPI produces Base64URL encoded strings in `jws` mode.

See the code here to produce those 
http://stackoverflow.com/questions/33642310/is-there-a-way-to-get-the-components-of-an-rsa-key-in-the-webcrypto-api

The following JS code does the trick to convert it

```JavaScript
function encodeURL(str){
    return str.replace(/\+/g, '-').replace(/\//g, '_').replace(/\=+$/, '');
}

function decodeUrl(str){
    str = (str + '===').slice(0, str.length + (str.length % 4));
    return str.replace(/-/g, '+').replace(/_/g, '/');
}
```

and then one can use `window.atob`

I tried the library here, but it gives an error

**Comment by marklister** [comment]
Thanks for the report. I'm keen to fix the problem but given that I don't do more than basic Javascript maybe you could go into a bit more detail on the actual encoding problem.

You obviously [brought the correct implicit into scope](https://github.com/marklister/base64#encoding-base64-vs-base64url)?

I'm also in the dark about "jws mode".  A quick google didn't enlighten me.

**Comment by marklister** [comment]
It could be a padding problem.  Try adding two "=" on the end of your modulus and it works.  I guess I could make padding less strict.  You might also need to strip out "\n".  I'll have a look again at the RFC.

**Comment by bblfish** [comment]
just was in a meeting. I have just rewritten the code in Scala....

**Comment by bblfish** [comment]
This is what I am trying in the console.
First I copy the value from the JSON Web Key format http://tools.ietf.org/html/rfc7517

```javascript
var bu = "6XVlAWq2THhrk9AUERKH6O3D1dZty1C1GoUhgD56ALWgsFTYZ9fBbAb-2h0uKHNw4c8EqA4IAXnu1NAI25caDqx1TG4y1MKBZXVcbIc9MDrIcs2tRt-SlGVe1bgUVRcQHcbL2Rspp354XwF8aSISDvB4gKwK-VORN9QojbdJUi9P4kyAAzhC4u_HkS0UySVqirIxb5hzcIZJiAzaEq6zouKcZ6wtgF60gVPAvPCQZ5Xkno4HUGsPoq4ZCLPctuYCEOWlMdG_Fnd7phi2iXjwhqvGsqM4rEFAb0kqZr1J_xbCUPTl4uVc_AEw-9_3AWutplsQfSH8r5sFkflz69tFyw"
> window.atob(bu)
VM498:2 Uncaught DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.(…)
> var u = decodeUrl(bu)
"6XVlAWq2THhrk9AUERKH6O3D1dZty1C1GoUhgD56ALWgsFTYZ9fBbAb+2h0uKHNw4c8EqA4IAXnu1NAI25caDqx1TG4y1MKBZXVcbIc9MDrIcs2tRt+SlGVe1bgUVRcQHcbL2Rspp354XwF8aSISDvB4gKwK+VORN9QojbdJUi9P4kyAAzhC4u/HkS0UySVqirIxb5hzcIZJiAzaEq6zouKcZ6wtgF60gVPAvPCQZ5Xkno4HUGsPoq4ZCLPctuYCEOWlMdG/Fnd7phi2iXjwhqvGsqM4rEFAb0kqZr1J/xbCUPTl4uVc/AEw+9/3AWutplsQfSH8r5sFkflz69tFyw=="
> window.atob(u)
"éuej¶LxkÐèíÃÕÖmËPµ!>zµ °TØg×ÁlþÚ.(spáÏ¨yîÔÐÛ¬uLn2ÔÂeu\l=0:ÈrÍ­Fße^Õ¸UÆËÙ)§~x_|i"ðx¬
ùS7Ô(·IR/OâL8BâïÇ-É%j²1ospIÚ®³¢âg¬-^´SÀ¼ðgäPk¢®³Ü¶æå¥1Ñ¿w{¦¶xð«Æ²£8¬A@oI*f½IÿÂPôåâå\ü0ûß÷k­¦[}!ü¯ùsëÛEË"
```

**Comment by bblfish** [comment]
The easiest way to run the JS is to just go to a web page with an https url, and enter the JS in the console, in a very new browser ( Chrome ).

**Comment by marklister** [comment]
Thanks for your help debugging this.  As you already discovered it's a padding problem coupled with the use of the default base64 encoder instead of the base64Url encoder.

I think (i need to work out some better tests) that I've fixed this and will push it to a branch called nonStrictPadding shortly.  I'd appreciate your feedback.  Here's a REPL session:

```scala
> base64JVM/console
[info] Compiling 1 Scala source to /home/mark/scalaProjects/base64/jvm/target/scala-2.11/classes...
[info] Starting scala interpreter...
[info] 
Welcome to Scala version 2.11.7 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_66).
Type in expressions to have them evaluated.
Type :help for more information.

scala> import com.github.marklister.base64.Base64._
import com.github.marklister.base64.Base64._

scala> implicit val encoding = base64Url
encoding: com.github.marklister.base64.Base64.B64Scheme = com.github.marklister.base64.Base64$B64Scheme@7c006696

scala> var bu = "6XVlAWq2THhrk9AUERKH6O3D1dZty1C1GoUhgD56ALWgsFTYZ9fBbAb-2h0uKHNw4c8EqA4IAXnu1NAI25caDqx1TG4y1MKBZXVcbIc9MDrIcs2tRt-SlGVe1bgUVRcQHcbL2Rspp354XwF8aSISDvB4gKwK-VORN9QojbdJUi9P4kyAAzhC4u_HkS0UySVqirIxb5hzcIZJiAzaEq6zouKcZ6wtgF60gVPAvPCQZ5Xkno4HUGsPoq4ZCLPctuYCEOWlMdG_Fnd7phi2iXjwhqvGsqM4rEFAb0kqZr1J_xbCUPTl4uVc_AEw-9_3AWutplsQfSH8r5sFkflz69tFyw"
bu: String = 6XVlAWq2THhrk9AUERKH6O3D1dZty1C1GoUhgD56ALWgsFTYZ9fBbAb-2h0uKHNw4c8EqA4IAXnu1NAI25caDqx1TG4y1MKBZXVcbIc9MDrIcs2tRt-SlGVe1bgUVRcQHcbL2Rspp354XwF8aSISDvB4gKwK-VORN9QojbdJUi9P4kyAAzhC4u_HkS0UySVqirIxb5hzcIZJiAzaEq6zouKcZ6wtgF60gVPAvPCQZ5Xkno4HUGsPoq4ZCLPctuYCEOWlMdG_Fnd7phi2iXjwhqvGsqM4rEFAb0kqZr1J_xbCUPTl4uVc_AEw-9_3AWutplsQfSH8r5sFkflz69tFyw

scala> bu.toByteArray
res0: Array[Byte] = Array(-23, 117, 101, 1, 106, -74, 76, 120, 107, -109, -48, 20, 17, 18, -121, -24, -19, -61, -43, -42, 109, -53, 80, -75, 26, -123, 33, -128, 62, 122, 0, -75, -96, -80, 84, -40, 103, -41, -63, 108, 6, -2, -38, 29, 46, 40, 115, 112, -31, -49, 4, -88, 14, 8, 1, 121, -18, -44, -48, 8, -37, -105, 26, 14, -84, 117, 76, 110, 50, -44, -62, -127, 101, 117, 92, 108, -121, 61, 48, 58, -56, 114, -51, -83, 70, -33, -110, -108, 101, 94, -43, -72, 20, 85, 23, 16, 29, -58, -53, -39, 27, 41, -89, 126, 120, 95, 1, 124, 105, 34, 18, 14, -16, 120, -128, -84, 10, -7, 83, -111, 55, -44, 40, -115, -73, 73, 82, 47, 79, -30, 76, -128, 3, 56, 66, -30, -17, -57, -111, 45, 20, -55, 37, 106, -118, -78, 49, 111, -104, 115, 112, -122, 73, -120, 12, -38, 18, -82, -77, -94, -30, -100, 103, -84, 45, ...
```

**Comment by marklister** [comment]
Embarrassingly this is mentioned in #4 and #5 too.  Will publish this fix as a priority.

**Comment by bblfish** [comment]
Perhaps there is an extra improvement you can add. Is it possible to abstract somewhat from an array? For example the JS seems to return a [ArrayBuffer](https://github.com/scala-js/scala-js/blob/master/library/src/main/scala/scala/scalajs/js/typedarray/ArrayBuffer.scala) which I think can be turned into a java.nio.ByteBuffer using [TypedArrayBufferBridge](https://github.com/scala-js/scala-js/blob/master/library/src/main/scala/scala/scalajs/js/typedarray/TypedArrayBufferBridge.scala).

So it would be useful to have a method that could work with those elements and not just arrays. I am not yet quite sure what the best abstraction here would be... Certainly given that you don't need to change the source object, an Array is too precise.

**Comment by marklister** [comment]
This won't hit Maven Central for a week (left my keys at home).  But it's publish unsigned on Bintray.

**Comment by bblfish** [comment]
thanks, I have moved to using this code.

**Comment by marklister** [comment]
Performance is much improved in the latest iteration.  I'm travelling the next few days but will finialize those changes next week and push a release at the same time.  Unfortunately it involves directly addressing arrays etc which reduces safety a little, however I think there's one unreported bug I may have fixed.

**Comment by bblfish** [comment]
Is there an iteration more recent than the one 3 days ago? Trying to debug some cryptography here, and so any bug fix will help :-)

**Comment by marklister** [comment]
I can push to master if you like? It's a bit rough.

**Comment by bblfish** [comment]
perhaps on a branch, then I can see if it helps me, but come back in case something goes wrong. :-)

**Comment by bblfish** [comment]
I have tested everything now ( fixed a number of bugs ) and all that remains is potentially a base64 encoding error. So if you push something I'll try it immediately :-)

**Comment by bblfish** [comment]
I used msseddon's Base64 class linked above and it gives the same result as yours, so unless his is also broken in the same way yours is, then my bug is somewhere else...

**Comment by marklister** [comment]
here:

package com.github.marklister.base64

import scala.collection.mutable.ArrayBuilder

/**
  * Base64 encoder
  * @author Mark Lister
  *         This software is distributed under the 2-Clause BSD license. See the
  *         LICENSE file in the root of the repository.
  *
  *         Copyright (c) 2014 - 2015 Mark Lister
  *
  *         The repo for this Base64 encoder lives at  https://github.com/marklister/base64
  *         Please send your issues, suggestions and pull requests there.
  */

object Base64 {

  case class B64Scheme(encodeTable: Array[Char], strictPadding: Boolean = true) {
    lazy val decodeTable = {
      val b: Array[Int] = new Array[Int](256)
      for (x <- encodeTable.zipWithIndex) {
        b(x._1) = x._2.toInt
      }
      b
    }
  }

  val base64 = new B64Scheme((('A' to 'Z') ++ ('a' to 'z') ++ ('0' to '9') ++ Seq('+', '/')).toArray)
  val base64Url = new B64Scheme(base64.encodeTable.dropRight(2) ++ Seq('-', '_'), false)

  implicit class SeqEncoder(s: Seq[Byte]) {
    def toBase64(implicit scheme: B64Scheme = base64): String = Encoder(s.toArray).toBase64
  }

  implicit class Encoder(b: Array[Byte]) {
    val r = new StringBuilder((b.length + 3) * 4 / 3)
    lazy val pad = (3 - b.length % 3) % 3

    def toBase64(implicit scheme: B64Scheme = base64): String = {
      def sixBits(x: Byte, y: Byte, z: Byte): Unit = {
        val zz = (x & 0xff) << 16 | (y & 0xff) << 8  | (z & 0xff)
        r += scheme.encodeTable(zz >> 18)
        r += scheme.encodeTable(zz >> 12 & 0x3f)
        r += scheme.encodeTable(zz >> 6 & 0x3f)
        r += scheme.encodeTable(zz & 0x3f)
      }
      for (p <- 0 until b.length - 2 by 3) {
        sixBits(b(p), b(p + 1), b(p + 2))
      }
      pad match {
        case 0 =>
        case 1 => sixBits(b(b.length - 2), b(b.length - 1), 0)
        case 2 => sixBits(b(b.length - 1), 0, 0)
      }
      r.length = (r.length - pad)
      r ++= "=" * pad
      r.toString()
    }
  }

  implicit class Decoder(s: String) {
    lazy val cleanS = s.replaceAll("=+$", "")
    lazy val pad = s.length - cleanS.length
    lazy val computedPad = (4 - (cleanS.length % 4)) % 4

    def toByteArray(implicit scheme: B64Scheme = base64): Array[Byte] = {
      val r = new ArrayBuilder.ofByte

      def threeBytes(a: Int, b: Int, c: Int, d: Int): Unit = {
        val i = a << 18 | b << 12 | c << 6 | d
        r += ((i >> 16).toByte)
        r += ((i >> 8).toByte)
        r += (i.toByte)
      }
      if (scheme.strictPadding) {
        if (pad > 2) throw new java.lang.IllegalArgumentException("Invalid Base64 String: (excessive padding) " + s)
        if (s.length % 4 != 0) throw new java.lang.IllegalArgumentException("Invalid Base64 String: (padding problem) " + s)
      }
      if (computedPad == 3) throw new java.lang.IllegalArgumentException("Invalid Base64 String: (string length) " + s)
      try {
        val s = (cleanS + "A" * computedPad)
        for (x <- 0 until s.length - 1 by 4) {
          val i = scheme.decodeTable(s.charAt(x)) << 18 |
            scheme.decodeTable(s.charAt(x + 1)) << 12 |
            scheme.decodeTable(s.charAt(x + 2)) << 6 |
            scheme.decodeTable(s.charAt(x + 3))
          r += ((i >> 16).toByte)
          r += ((i >> 8).toByte)
          r += (i.toByte)
        }
      } catch {
        case e: NoSuchElementException => throw new java.lang.IllegalArgumentException("Invalid Base64 String: (invalid character)" + e.getMessage + s)
      }
      val res = r.result
      res.slice(0, res.length - computedPad)
    }

  }

}

**Comment by marklister** [comment]
It's messy but passes all the tests.

**Comment by marklister** [comment]
Pretty fast though.
